// generated by Color Variables Exporter Sketch Plugin

import UIKit

extension UIColor {
    /// #361D32 - 100%
    static let appKey: UIColor = UIColor(named: "app_key")!

    /// #543C52 - 100%
    static let appKeyLight: UIColor = UIColor(named: "app_key_light")!

    /// #F55951 - 100%
    static let appAccent: UIColor = UIColor(named: "app_accent")!

    /// #EDD2CB - 100%
    static let appBase: UIColor = UIColor(named: "app_base")!

    /// #F1E8E6 - 100%
    static let appBaseLight: UIColor = UIColor(named: "app_base_light")!

    /// #FFA822 - 100%
    static let retroOrange: UIColor = UIColor(named: "retro_orange")!

    /// #134E6F - 100%
    static let retroDarkBlue: UIColor = UIColor(named: "retro_dark_blue")!

    /// #FF6150 - 100%
    static let retroPink: UIColor = UIColor(named: "retro_pink")!

    /// #1AC0C6 - 100%
    static let retroLightBlue: UIColor = UIColor(named: "retro_light_blue")!

    /// #DEE0E6 - 100%
    static let retroGray: UIColor = UIColor(named: "retro_gray")!

}